### ISSUE TITLE
Negative delay corrupts(?) the file

### ISSUE THREAD

**Issue by vevv** [MonoS/SupMover#22]
After adding a negative delay, and remuxing in MKVToolnix, the file ends up with 10+ hour duration in MediaInfo.
Oddly, loading a file processed with SupMover in Subtitle Edit, shows it was applied correctly, and if I resave it in Subtitle Edit, then mux, it turns out correctly. This happened to me with multiple files, from different sources, but only with negative delay, not positive.

Command: `SupMover.exe "00001 - 7 - Subtitle (PGS), German, 988 captions.sup" ger.sup --delay -542`

**Comment by MonoS** [comment]
Could you upload one of the sup that0s giving you problem?

What I think is happening is that there is a subpic before the 542ms and my program is not checking for boundary condition so is underflowing generating the big timestamp.

**Comment by MonoS** [comment]
Yeah, what i expected
![immagine](https://github.com/user-attachments/assets/bb7084f1-b745-4b5c-a73f-0a1426359017)
I've pushed a new version that will fix it
