### ISSUE TITLE
[Feature Request] Resize subtitles

### ISSUE THREAD

**Issue by vevv** [MonoS/SupMover#23]
It would be great to resize subtitles to match lower resolution files. It would also render flawed BDSup2Sub truly redundant.

**Comment by MonoS** [comment]
Hi @vevv, i don't think it will be possible, the purpose of this tool is to do changes to SUP files in a as-lossless-as-possible way, it was never its purpose to substitute BDSup2Sub entirely as resizing would mean to recreate the image data and the palette and a GUI is necessary to check the output before saving (or you could check it directly on the video, but that's another point).
In theory it should be possible, a `resize` option with a percentage value and the image will be automatically resized then dithered to 255 colors, but then you could add multiple resizing kernel, different dithering algos and complicate the codebase for something I don't think should be handled by this tool
