### ISSUE TITLE
关于tonemap功能的使用

### ISSUE THREAD

**Issue by mojie126** [MonoS/SupMover#6]
请问这个功能调整的亮度，1表示100%亮度，1.2表示120%亮度，0.8表示80%亮度，是这么个意思么？
另外此功能是否会改变图片显示质量？

**Comment by MonoS** [comment]
Hi, I had to machine translate your message as I don't know chinese, i hope to answer you question properly.
Yes, the `tonemap` parameters works as you stated, with 1 leaving the image unchanged, with a value bigger than 1 it will increase brightness and with a value lower than 1 it will lower it.
Regarding image quality it does not change any image data, sup subtitle have separated image data and color data, my implementation only change the color data (the Palette data) leaving the image data unchanged.

**Comment by mojie126** [comment]
Okay, thank you
I saw that your other warehouses use Chinese, so I thought you knew Chinese
